#!/bin/bash

# Comprehensive API Test Runner
# Runs all API tests and generates a report

echo "=========================================="
echo "   Clients+ API Comprehensive Testing"
echo "=========================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check if server is running
echo -e "${BLUE}Checking if API server is running...${NC}"
curl -s http://localhost:4000/health > /dev/null 2>&1
if [ $? -ne 0 ]; then
  echo -e "${RED}✗ API server is not running on port 3001${NC}"
  echo "Please start the server with: npm run dev"
  exit 1
fi
echo -e "${GREEN}✓ API server is running${NC}"

# Create results directory
RESULTS_DIR="test-results-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$RESULTS_DIR"

echo -e "\n${BLUE}Test results will be saved to: $RESULTS_DIR${NC}\n"

# Run authentication tests
echo -e "${YELLOW}Running Authentication Tests...${NC}"
bash auth-test.sh > "$RESULTS_DIR/auth-test.log" 2>&1
if [ $? -eq 0 ]; then
  echo -e "${GREEN}✓ Authentication tests completed${NC}"
else
  echo -e "${RED}✗ Authentication tests failed${NC}"
fi

# Run client management tests
echo -e "${YELLOW}Running Client Management Tests...${NC}"
bash client-test.sh > "$RESULTS_DIR/client-test.log" 2>&1
if [ $? -eq 0 ]; then
  echo -e "${GREEN}✓ Client tests completed${NC}"
else
  echo -e "${RED}✗ Client tests failed${NC}"
fi

# Run appointment tests
echo -e "${YELLOW}Running Appointment Tests...${NC}"
bash appointment-test.sh > "$RESULTS_DIR/appointment-test.log" 2>&1
if [ $? -eq 0 ]; then
  echo -e "${GREEN}✓ Appointment tests completed${NC}"
else
  echo -e "${RED}✗ Appointment tests failed${NC}"
fi

# Generate summary report
echo -e "\n${BLUE}Generating test summary...${NC}"

cat > "$RESULTS_DIR/summary.md" << EOF
# API Test Results Summary
**Date:** $(date)
**Server:** http://localhost:4000

## Test Results

### Authentication Tests
\`\`\`
$(grep -E "✓|✗|⚠" "$RESULTS_DIR/auth-test.log" || echo "No results")
\`\`\`

### Client Management Tests
\`\`\`
$(grep -E "✓|✗|⚠" "$RESULTS_DIR/client-test.log" || echo "No results")
\`\`\`

### Appointment Tests
\`\`\`
$(grep -E "✓|✗|⚠" "$RESULTS_DIR/appointment-test.log" || echo "No results")
\`\`\`

## Issues Found

### Critical Issues
$(grep -E "✗" "$RESULTS_DIR"/*.log | wc -l) failures detected

### Warnings
$(grep -E "⚠" "$RESULTS_DIR"/*.log | wc -l) warnings detected

## Recommendations
1. Fix any failing endpoints before deployment
2. Address warnings for better compatibility
3. Ensure all frontend-expected endpoints are available

---
*Generated by Clients+ API Test Suite*
EOF

# Display summary
echo ""
echo "=========================================="
echo "           Test Summary"
echo "=========================================="
echo ""

TOTAL_TESTS=$(grep -E "Test [0-9]+" "$RESULTS_DIR"/*.log | wc -l)
PASSED_TESTS=$(grep -E "✓" "$RESULTS_DIR"/*.log | wc -l)
FAILED_TESTS=$(grep -E "✗" "$RESULTS_DIR"/*.log | wc -l)
WARNING_TESTS=$(grep -E "⚠" "$RESULTS_DIR"/*.log | wc -l)

echo -e "Total Tests Run: ${BLUE}$TOTAL_TESTS${NC}"
echo -e "Passed: ${GREEN}$PASSED_TESTS${NC}"
echo -e "Failed: ${RED}$FAILED_TESTS${NC}"
echo -e "Warnings: ${YELLOW}$WARNING_TESTS${NC}"
echo ""

if [ $FAILED_TESTS -eq 0 ]; then
  echo -e "${GREEN}All tests passed successfully!${NC}"
else
  echo -e "${RED}Some tests failed. Please review the logs in $RESULTS_DIR${NC}"
fi

echo ""
echo "Full results saved to: $RESULTS_DIR/summary.md"
echo ""